/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAdminRouteRouteImport } from './routes/admin/_admin/route'
import { Route as AdminAdminUserRouteImport } from './routes/admin/_admin/user'
import { Route as AdminAdminPresensiRouteImport } from './routes/admin/_admin/presensi'
import { Route as AdminAdminLogRouteImport } from './routes/admin/_admin/log'
import { Route as AdminAdminKelompokRouteImport } from './routes/admin/_admin/kelompok'
import { Route as AdminAdminKegiatanRouteImport } from './routes/admin/_admin/kegiatan'
import { Route as AdminAdminGenerusRouteImport } from './routes/admin/_admin/generus'
import { Route as AdminAdminDesaRouteImport } from './routes/admin/_admin/desa'
import { Route as AdminAdminDashboardRouteImport } from './routes/admin/_admin/dashboard'

const AdminRouteImport = createFileRoute('/admin')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUserRoute = AdminAdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminPresensiRoute = AdminAdminPresensiRouteImport.update({
  id: '/presensi',
  path: '/presensi',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminLogRoute = AdminAdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminKelompokRoute = AdminAdminKelompokRouteImport.update({
  id: '/kelompok',
  path: '/kelompok',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminKegiatanRoute = AdminAdminKegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminGenerusRoute = AdminAdminGenerusRouteImport.update({
  id: '/generus',
  path: '/generus',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminDesaRoute = AdminAdminDesaRouteImport.update({
  id: '/desa',
  path: '/desa',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/desa': typeof AdminAdminDesaRoute
  '/admin/generus': typeof AdminAdminGenerusRoute
  '/admin/kegiatan': typeof AdminAdminKegiatanRoute
  '/admin/kelompok': typeof AdminAdminKelompokRoute
  '/admin/log': typeof AdminAdminLogRoute
  '/admin/presensi': typeof AdminAdminPresensiRoute
  '/admin/user': typeof AdminAdminUserRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/desa': typeof AdminAdminDesaRoute
  '/admin/generus': typeof AdminAdminGenerusRoute
  '/admin/kegiatan': typeof AdminAdminKegiatanRoute
  '/admin/kelompok': typeof AdminAdminKelompokRoute
  '/admin/log': typeof AdminAdminLogRoute
  '/admin/presensi': typeof AdminAdminPresensiRoute
  '/admin/user': typeof AdminAdminUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/admin/_admin': typeof AdminAdminRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/_admin/desa': typeof AdminAdminDesaRoute
  '/admin/_admin/generus': typeof AdminAdminGenerusRoute
  '/admin/_admin/kegiatan': typeof AdminAdminKegiatanRoute
  '/admin/_admin/kelompok': typeof AdminAdminKelompokRoute
  '/admin/_admin/log': typeof AdminAdminLogRoute
  '/admin/_admin/presensi': typeof AdminAdminPresensiRoute
  '/admin/_admin/user': typeof AdminAdminUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/desa'
    | '/admin/generus'
    | '/admin/kegiatan'
    | '/admin/kelompok'
    | '/admin/log'
    | '/admin/presensi'
    | '/admin/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/desa'
    | '/admin/generus'
    | '/admin/kegiatan'
    | '/admin/kelompok'
    | '/admin/log'
    | '/admin/presensi'
    | '/admin/user'
  id:
    | '__root__'
    | '/admin'
    | '/admin/_admin'
    | '/admin/login'
    | '/admin/_admin/dashboard'
    | '/admin/_admin/desa'
    | '/admin/_admin/generus'
    | '/admin/_admin/kegiatan'
    | '/admin/_admin/kelompok'
    | '/admin/_admin/log'
    | '/admin/_admin/presensi'
    | '/admin/_admin/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_admin/user': {
      id: '/admin/_admin/user'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminAdminUserRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/presensi': {
      id: '/admin/_admin/presensi'
      path: '/presensi'
      fullPath: '/admin/presensi'
      preLoaderRoute: typeof AdminAdminPresensiRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/log': {
      id: '/admin/_admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AdminAdminLogRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/kelompok': {
      id: '/admin/_admin/kelompok'
      path: '/kelompok'
      fullPath: '/admin/kelompok'
      preLoaderRoute: typeof AdminAdminKelompokRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/kegiatan': {
      id: '/admin/_admin/kegiatan'
      path: '/kegiatan'
      fullPath: '/admin/kegiatan'
      preLoaderRoute: typeof AdminAdminKegiatanRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/generus': {
      id: '/admin/_admin/generus'
      path: '/generus'
      fullPath: '/admin/generus'
      preLoaderRoute: typeof AdminAdminGenerusRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/desa': {
      id: '/admin/_admin/desa'
      path: '/desa'
      fullPath: '/admin/desa'
      preLoaderRoute: typeof AdminAdminDesaRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/dashboard': {
      id: '/admin/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
  }
}

interface AdminAdminRouteRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminDesaRoute: typeof AdminAdminDesaRoute
  AdminAdminGenerusRoute: typeof AdminAdminGenerusRoute
  AdminAdminKegiatanRoute: typeof AdminAdminKegiatanRoute
  AdminAdminKelompokRoute: typeof AdminAdminKelompokRoute
  AdminAdminLogRoute: typeof AdminAdminLogRoute
  AdminAdminPresensiRoute: typeof AdminAdminPresensiRoute
  AdminAdminUserRoute: typeof AdminAdminUserRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminDesaRoute: AdminAdminDesaRoute,
  AdminAdminGenerusRoute: AdminAdminGenerusRoute,
  AdminAdminKegiatanRoute: AdminAdminKegiatanRoute,
  AdminAdminKelompokRoute: AdminAdminKelompokRoute,
  AdminAdminLogRoute: AdminAdminLogRoute,
  AdminAdminPresensiRoute: AdminAdminPresensiRoute,
  AdminAdminUserRoute: AdminAdminUserRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
