/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminLoginImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard/route'
import { Route as AdminDashboardIndexImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardRemajaImport } from './routes/admin/dashboard/remaja'
import { Route as AdminDashboardKelompokImport } from './routes/admin/dashboard/kelompok'
import { Route as AdminDashboardDesaImport } from './routes/admin/dashboard/desa'

// Create/Update Routes

const AdminLoginRoute = AdminLoginImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRouteRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardIndexRoute = AdminDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)

const AdminDashboardRemajaRoute = AdminDashboardRemajaImport.update({
  id: '/remaja',
  path: '/remaja',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)

const AdminDashboardKelompokRoute = AdminDashboardKelompokImport.update({
  id: '/kelompok',
  path: '/kelompok',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)

const AdminDashboardDesaRoute = AdminDashboardDesaImport.update({
  id: '/desa',
  path: '/desa',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard/desa': {
      id: '/admin/dashboard/desa'
      path: '/desa'
      fullPath: '/admin/dashboard/desa'
      preLoaderRoute: typeof AdminDashboardDesaImport
      parentRoute: typeof AdminDashboardRouteImport
    }
    '/admin/dashboard/kelompok': {
      id: '/admin/dashboard/kelompok'
      path: '/kelompok'
      fullPath: '/admin/dashboard/kelompok'
      preLoaderRoute: typeof AdminDashboardKelompokImport
      parentRoute: typeof AdminDashboardRouteImport
    }
    '/admin/dashboard/remaja': {
      id: '/admin/dashboard/remaja'
      path: '/remaja'
      fullPath: '/admin/dashboard/remaja'
      preLoaderRoute: typeof AdminDashboardRemajaImport
      parentRoute: typeof AdminDashboardRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexImport
      parentRoute: typeof AdminDashboardRouteImport
    }
  }
}

// Create and export the route tree

interface AdminDashboardRouteRouteChildren {
  AdminDashboardDesaRoute: typeof AdminDashboardDesaRoute
  AdminDashboardKelompokRoute: typeof AdminDashboardKelompokRoute
  AdminDashboardRemajaRoute: typeof AdminDashboardRemajaRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardDesaRoute: AdminDashboardDesaRoute,
  AdminDashboardKelompokRoute: AdminDashboardKelompokRoute,
  AdminDashboardRemajaRoute: AdminDashboardRemajaRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard/desa': typeof AdminDashboardDesaRoute
  '/admin/dashboard/kelompok': typeof AdminDashboardKelompokRoute
  '/admin/dashboard/remaja': typeof AdminDashboardRemajaRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard/desa': typeof AdminDashboardDesaRoute
  '/admin/dashboard/kelompok': typeof AdminDashboardKelompokRoute
  '/admin/dashboard/remaja': typeof AdminDashboardRemajaRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard/desa': typeof AdminDashboardDesaRoute
  '/admin/dashboard/kelompok': typeof AdminDashboardKelompokRoute
  '/admin/dashboard/remaja': typeof AdminDashboardRemajaRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/dashboard/desa'
    | '/admin/dashboard/kelompok'
    | '/admin/dashboard/remaja'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/login'
    | '/admin/dashboard/desa'
    | '/admin/dashboard/kelompok'
    | '/admin/dashboard/remaja'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/dashboard/desa'
    | '/admin/dashboard/kelompok'
    | '/admin/dashboard/remaja'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/admin/dashboard",
        "/admin/login"
      ]
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard/route.tsx",
      "children": [
        "/admin/dashboard/desa",
        "/admin/dashboard/kelompok",
        "/admin/dashboard/remaja",
        "/admin/dashboard/"
      ]
    },
    "/admin/login": {
      "filePath": "admin/login.tsx"
    },
    "/admin/dashboard/desa": {
      "filePath": "admin/dashboard/desa.tsx",
      "parent": "/admin/dashboard"
    },
    "/admin/dashboard/kelompok": {
      "filePath": "admin/dashboard/kelompok.tsx",
      "parent": "/admin/dashboard"
    },
    "/admin/dashboard/remaja": {
      "filePath": "admin/dashboard/remaja.tsx",
      "parent": "/admin/dashboard"
    },
    "/admin/dashboard/": {
      "filePath": "admin/dashboard/index.tsx",
      "parent": "/admin/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
