/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminLoginImport } from './routes/admin/login'
import { Route as AdminDashboardIndexImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardRemajaImport } from './routes/admin/dashboard/remaja'

// Create/Update Routes

const AdminLoginRoute = AdminLoginImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardIndexRoute = AdminDashboardIndexImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRemajaRoute = AdminDashboardRemajaImport.update({
  id: '/admin/dashboard/remaja',
  path: '/admin/dashboard/remaja',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard/remaja': {
      id: '/admin/dashboard/remaja'
      path: '/admin/dashboard/remaja'
      fullPath: '/admin/dashboard/remaja'
      preLoaderRoute: typeof AdminDashboardRemajaImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard/remaja': typeof AdminDashboardRemajaRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard/remaja': typeof AdminDashboardRemajaRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard/remaja': typeof AdminDashboardRemajaRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/admin/login' | '/admin/dashboard/remaja' | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin/login' | '/admin/dashboard/remaja' | '/admin/dashboard'
  id:
    | '__root__'
    | '/admin/login'
    | '/admin/dashboard/remaja'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminDashboardRemajaRoute: typeof AdminDashboardRemajaRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminDashboardRemajaRoute: AdminDashboardRemajaRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/admin/login",
        "/admin/dashboard/remaja",
        "/admin/dashboard/"
      ]
    },
    "/admin/login": {
      "filePath": "admin/login.tsx"
    },
    "/admin/dashboard/remaja": {
      "filePath": "admin/dashboard/remaja.tsx"
    },
    "/admin/dashboard/": {
      "filePath": "admin/dashboard/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
